# Generated by Django 3.1.6 on 2021-05-31 00:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TaskManagementApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tododb',
            name='timetaken',
            field=models.DateField(default=datetime.datetime(2021, 5, 31, 5, 53, 53, 309434)),
        ),
    ]
