# Generated by Django 3.1.6 on 2021-06-13 12:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TaskManagementApp', '0002_auto_20210531_0553'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.AlterField(
            model_name='tododb',
            name='timetaken',
            field=models.DateField(default=datetime.datetime(2021, 6, 13, 18, 3, 47, 128206)),
        ),
    ]
